
modLoader="javafml" #mandatory
loaderVersion="[35,)" 
license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="examplemod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Example Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
#authors="Love, Cheese and small house plants" #optional
description='''
My first silly mod.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
